services:
  discordbot-webpage-status:
    image: ghcr.io/zamnzim/discordbot-webpage-status:latest
    environment:
      - DISCORD_TOKEN=your_discord_bot_token_here
    volumes:
      - websites-data:/app/data #Location for SQL Database
    restart: unless-stopped

volumes:

  websites-data:
